services:
    snowballr-mock-backend:
        build: .
        ports:
            - "8081:8080"
    envoy-proxy:
        image: envoyproxy/envoy:v1.33.0
        ports:
            - "8080:8080"
        volumes:
            - ./envoy.yaml:/etc/envoy/envoy.yaml
